
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-billing-source
  namespace: default
  labels:
    app: aws-billing-source
spec:
  selector:
    matchLabels:
      app: aws-billing-source
  template:
    metadata:
      labels:
        app: aws-billing-source
    spec:
      containers:
        - name: aws-billing-source
          image: docker.io/vancehub/source-aws-billing
          imagePullPolicy: IfNotPresent
          env:
          - name: V_TARGET
            value: http://vanus-gateway.vanus:8080/gateway/tutorials
          - name: ACCESS_KEY_ID
            value: <YOUR ACCESS_KEY_ID>
          - name: SECRET_ACCESS_KEY
            value: <YOUR SECRET_ACCESS_KEY> 
    
