# Copyright 2022 Linkall Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-grafana-sink
  labels:
    app: elasticsearch-grafana-sink
spec:
  selector:
    app: elasticsearch-grafana-sink
  ports:
    - port: 8080
      name: elasticsearch-grafana-sink
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-grafana-sink
  labels:
    app: elasticsearch-grafana-sink
spec:
  selector:
    matchLabels:
      app: elasticsearch-grafana-sink
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch-grafana-sink
    spec:
      containers:
        - name: elasticsearch-sink
          image: vancehub/sink-elasticsearch:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: ADDRESS
            value: <YOUR ADDRESS>
          - name: USERNAME
            value: <YOUR USERNAME>
          - name: PASSWORD
            value: <YOUR PASSWORD>
          - name: INDEX_NAME
            value: grafana
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 8080