
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-webhook-source
  namespace: default
  labels:
    app: http-webhook-source
spec:
  selector:
    matchLabels:
      app: http-webhook-source
  template:
    metadata:
      labels:
        app: http-webhook-source
    spec:
      containers:
        - name: http-webhook-source
          image: docker.io/vancehub/source-http
          imagePullPolicy: IfNotPresent
          env:
          - name: V_TARGET
            value: "http://vanus-gateway.vanus:8080/gateway/tutorials"
---
apiVersion: v1
kind: Service
metadata:
  name: http-webhook-source
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: http-webhook-source
  type: ClusterIP
